### ISSUE TITLE
Docs: provide hotkeys documentation

### ISSUE THREAD

**Issue by AnatolyRugalev** [AnatolyRugalev/kube-commander#36]
We need to provide more information about usage of kube-commander. Table of hotkeys in README.md should be enough I think

**Comment by mozai** [comment]
A little guide for how to use it and what keys to press while using it would really help.  the "C-B" at the bottom where it usually says "F5" had me pressing the "C" and "B" keys, then "Ctrl with Backspace".  My latest guess it it means "Ctrl with ← " but I can't be sure I'm not actvating some other hotkey.

**Comment by AnatolyRugalev** [comment]
@mozai thank you for feedback.

C-B is an abbreviation for Ctrl+B. I just took this kind of notation from Midnight Commander.

For sure, this aspects need documentation and your feedback motivates me to do things.
