### ISSUE TITLE
Windows: color scheme

### ISSUE THREAD

**Issue by AnatolyRugalev** [AnatolyRugalev/kube-commander#41]
Default 256-color theme doesn't work properly on Windows

**Comment by AnatolyRugalev** [comment]
I think we need to perform detection of color range of terminal and apply 256 or 16 -color theme accordingly

**Comment by amelkikh** [comment]
![image](https://user-images.githubusercontent.com/5112566/74880641-4b213280-5374-11ea-9479-1bd733ba353a.png)
The issue looks like this.
Could you fix that ASAP?
