### ISSUE TITLE
Bug: "context was not found for specified context"

### ISSUE THREAD

**Issue by mozai** [AnatolyRugalev/kube-commander#55]
Getting "context was not found for specified context" or "context does not exist" when using kube-commander.

1. start kube-commander
2. ask to 'D'escribe any namespace

**Expected behavior**
Same as if I typed `kubectl describe namespace $name` when not using kube-commander

**Screenshots or logs**
```
$ kubectl config current-context
alpha.k8s.local
$ kubectl describe namespace kube-public
Name:         kube-public
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
```
but using kube-commander
```
$ kube-commander 
Error in configuration: context was not found for specified context: alpha.k8s.local
```

**Desktop (please complete the following information):**
 - OS: Debian 9.11 "stretch"
 - terminal: xcfe4-terminal, but I'm going to a remote machine over ssh and launching there

**Additional context**
I don't have the config for all my clusters in $HOME/.kube/config , instead I have a config file for each cluster and I set KUBECONFIG to mention each one.

**Comment by AnatolyRugalev** [comment]
This issue is related to kubernetes versioning. I updated kubectl dependencies since your report, so you could try again.

Thank you

**Comment by mozai** [comment]
Tested with v0.2.0.  'D'escribe when browsing Namespaces does give the properties of a Namespace-type resource.
