### ISSUE TITLE
Feature: better pager for kubectl output

### ISSUE THREAD

**Issue by mozai** [AnatolyRugalev/kube-commander#56]
**Is your feature request related to a problem? Please describe.**
When I ask for the 'D'escription of a resource, if the description is less than one window in height, the screen will flicker and return to the kube-commander interface.  There's no time to read the output of kubectl... especially I get a one-line error message like "context does not exist" (see #55)

**Describe the solution you'd like**
When launching kubectl to show the human something, wait for the human to press a key before dismissing the kubectl output and returning to the kube-commander UI.  A blank line between sequential uses would be nice, just to hint at where the output of the latest command starts.

**Describe alternatives you've considered**
- Tried setting the PAGER envvar, in the hope that kubectl would pipe output to /usr/bin/less.  
- Alias the 'kubectl' command to `kubectl "$@" |less` -- didn't work because kube-commander doesn't launch kubectl in the same shell.
- maybe I should install a kubectl plugin that pipes all output to $PAGER ?

**Comment by AnatolyRugalev** [comment]
Since 0.2.0 you can define your pager now with PAGER env of --pager flag. Thanks for the idea!
