### ISSUE TITLE
Bug: Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by brl0** [AnatolyRugalev/kube-commander#70]
**Describe the bug**
Error: no Auth Provider found for name "gcp"

**To Reproduce**
1. Configure kubectl to access a GCP cluster.
2. Download kube-commander
3. Run kube-commander

**Expected behavior**
kube-commander to work

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster), Windows 10
 - Terminal emulator: Windows Terminal, Chrome/xterm.js

**Additional context**
Can't get kube-commander to run against a GCP kubernetes cluster.  kubectl works fine.

**Comment by AnatolyRugalev** [comment]
Thank you for report.

I will definitely look into it as soon as I have time for this project

**Comment by AnatolyRugalev** [comment]
Hey @brl0!

The issue was fixed in 0.2.2

Have a nice day!
