### ISSUE TITLE
License switch from MIT to Apache 2.0

### ISSUE THREAD

**Issue by AnatolyRugalev** [AnatolyRugalev/kube-commander#81]
I'm looking forward to switch kube-commander's license to Apache 2.0 to comply with [CNCF recommendatoin](https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/)

This requires me to ask explicit agreement for this actions from all contirubtors. Fortunately, there's only one.

@ssetin are you ok with license switch?

**Comment by ssetin** [comment]
that's ok
